""" Initial Supabase migration module 4

Revision ID: 17f38e37c428
Revises: 
Create Date: 2026-06-21 04:15:37.075549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f38e37c428'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('hospital_id', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_hospital_id'), 'audit_logs', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('complaints',
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('MEDICAL_ERROR', 'PRIVACY_ISSUE', 'BEHAVIORAL_ISSUE', 'UNAUTHORIZED_ACCESS', 'INCORRECT_UPDATE', 'OTHER', name='complaintcategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'ESCALATED', name='complaintstatus'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='complaintpriority'), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_index(op.f('ix_complaints_doctor_id'), 'complaints', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_complaints_hospital_id'), 'complaints', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_complaints_patient_id'), 'complaints', ['patient_id'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_table('emergency_overrides',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='overridestatus'), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('access_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_emergency_overrides_doctor_id'), 'emergency_overrides', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_emergency_overrides_hospital_id'), 'emergency_overrides', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_emergency_overrides_patient_id'), 'emergency_overrides', ['patient_id'], unique=False)
    op.create_index(op.f('ix_emergency_overrides_status'), 'emergency_overrides', ['status'], unique=False)
    op.create_table('hospital_metrics',
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('hospital_name', sa.String(), nullable=True),
    sa.Column('total_doctors', sa.Integer(), nullable=True),
    sa.Column('total_patients', sa.Integer(), nullable=True),
    sa.Column('total_complaints', sa.Integer(), nullable=True),
    sa.Column('open_complaints', sa.Integer(), nullable=True),
    sa.Column('total_alerts', sa.Integer(), nullable=True),
    sa.Column('active_alerts', sa.Integer(), nullable=True),
    sa.Column('total_overrides', sa.Integer(), nullable=True),
    sa.Column('avg_trust_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('hospital_id')
    )
    op.create_table('ledger_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('event_data', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('previous_hash', sa.String(), nullable=False),
    sa.Column('current_hash', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_ledger_events_current_hash'), 'ledger_events', ['current_hash'], unique=True)
    op.create_index(op.f('ix_ledger_events_event_type'), 'ledger_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_ledger_events_sequence_number'), 'ledger_events', ['sequence_number'], unique=True)
    op.create_index(op.f('ix_ledger_events_timestamp'), 'ledger_events', ['timestamp'], unique=False)
    op.create_table('security_alerts',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=True),
    sa.Column('alert_type', sa.Enum('REPEATED_ACCESS', 'ABNORMAL_DOWNLOAD', 'EXCESSIVE_VIEWS', 'OVERRIDE_ABUSE', 'OTHER_ANOMALY', name='alerttype'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'DISMISSED', 'UNDER_REVIEW', 'ESCALATED', name='alertstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_security_alerts_created_at'), 'security_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_alerts_hospital_id'), 'security_alerts', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_security_alerts_status'), 'security_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_security_alerts_user_id'), 'security_alerts', ['user_id'], unique=False)
    op.create_table('trust_scores',
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_index(op.f('ix_trust_scores_hospital_id'), 'trust_scores', ['hospital_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trust_scores_hospital_id'), table_name='trust_scores')
    op.drop_table('trust_scores')
    op.drop_index(op.f('ix_security_alerts_user_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_status'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_hospital_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_created_at'), table_name='security_alerts')
    op.drop_table('security_alerts')
    op.drop_index(op.f('ix_ledger_events_timestamp'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_sequence_number'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_event_type'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_current_hash'), table_name='ledger_events')
    op.drop_table('ledger_events')
    op.drop_table('hospital_metrics')
    op.drop_index(op.f('ix_emergency_overrides_status'), table_name='emergency_overrides')
    op.drop_index(op.f('ix_emergency_overrides_patient_id'), table_name='emergency_overrides')
    op.drop_index(op.f('ix_emergency_overrides_hospital_id'), table_name='emergency_overrides')
    op.drop_index(op.f('ix_emergency_overrides_doctor_id'), table_name='emergency_overrides')
    op.drop_table('emergency_overrides')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_patient_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_hospital_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_doctor_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_hospital_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
